### ISSUE TITLE
functions that take a Rawfd should be unsafe

### ISSUE THREAD

**Issue by bonzini** [rust-vmm/kvm#39]
This crate allows registering eventfds with the kernel from safe code, but that function takes a raw file descriptor, and has no way to check that that the VM will not outlive the file descriptor. Thus, register_ioevent and register_irqfd should be unsafe (I didn't check if there are more instances).

**Comment by andreeaflorescu** [comment]
We have two options here:
1. Mark register_ioevent and register_irqfd as unsafe
2. Use `EventFd` from vmm-sys-utils

The reason I replaced `EventFd` with `RawFd` was because I didn't want to take a dependency on vmm-sys-utils since we are using the eventfd as a rawfd anyway.

Any opinions on this one? @sameo @bonzini @alexandruag

**Comment by bonzini** [comment]
Yes, using `EventFd` would be better (and safe). However, to do it properly would require to pass a `&EventFd`, so please first check in Firecracker that it would be easy to pass the EventFd object by reference there.

**Comment by andreeaflorescu** [comment]
@bonzini That was the initial implementation in Firecracker, so it shouldn't be hard to switch back to it.

**Comment by andreeaflorescu** [comment]
About the dependency on vmm-sys-utils, nvm my brain was not functioning properly. We will take the dependency anyway since we are going to use the ioctls macro defines so I might as well just use a reference to EventFd.

**Comment by andreeaflorescu** [comment]
Fixed by #68
