### ISSUE TITLE
test_clock fails intermittently

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm#69]
Output of failing test here: https://buildkite.com/rust-vmm/kvm-ioctls-ci/builds/338#6553ffb7-00fe-426b-9fa1-6340caacfdab

This issue needs scoping.

**Comment by acatangiu** [comment]
This test intermittently fails on slow machines, when run under `kcov` (which slows things down even more).

```rust
    #[test]
    fn test_clock() {
        let kvm = Kvm::new().unwrap();
        let vm = kvm.create_vm().unwrap();

        // Get current time.
        let orig = vm.get_clock().unwrap();

        // Reset time.
        let mut fudged = kvm_clock_data::default();
        fudged.clock = 10;
        vm.set_clock(&fudged).unwrap();

        // Get new time.
        let new = vm.get_clock().unwrap();

        // Verify new time has progressed but is smaller than orig time.
        assert!(fudged.clock < new.clock);
        assert!(new.clock < orig.clock);
    }
```
I propose the following two options as a fix:

1. Introduce a `sleep` before `let orig = vm.get_clock().unwrap();` so that `orig` clock gets some extra cycles of advancement. This is kind of an ugly hack as it artificially increases test duration.
2. Just remove `orig`-related lines, only leave `fudged` and `new`. This should still provide good functionality testing and would remove dependency on the hardware speed of the machine the test is running on.

**Comment by andreeaflorescu** [comment]
These tests have exclusive access m5d.metal. What do you mean by slow?

**Comment by acatangiu** [comment]
I meant when it's run on a slow machine **or** under `kcov` which slows things down significantly.

**Comment by alxiord** [comment]
Hasn't been encountered for a while, please reopen if you come across it again.
