### ISSUE TITLE
[aarch64] Add test for create_irq_chip

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/kvm#79]
On aarch64 we initialize the interrupt controller using `create_device`. This can be achieved with `create_irq_chip()` as well. I believe it only works with GICv2 (need to double check when scoping this issue). We should also add a test with `create_irq_chip`.

**Comment by michael2012z** [comment]
Hi, @andreeaflorescu 

I am preparing a PR to fix this. But I think it's better to discuss at first.

I tested `KVM_CREATE_IRQCHIP` in different machines with GICv2 or GICv3. It looks like this IOCTL only works with GICv2. (I am not sure if this is expected behavior. I thought VGICv2 should also be emulated with GICv3 hardware. I will check more.)

I think a better way to use `create_irq_chip()` is checking if KVM has the ability to emulate VGICv2 ahead. In this way we are able to get rid of hardware dependency. We can do this by calling `create_device()` with `KVM_CREATE_DEVICE_TEST` flag.

Here is the working code:
```rust
    #[test]
    #[cfg(target_arch = "aarch64")]
    fn test_irq_chip() {
        use Cap;

        let kvm = Kvm::new().unwrap();
        assert!(kvm.check_extension(Cap::Irqchip));

        let vm = kvm.create_vm().unwrap();

        let mut gic_device = kvm_bindings::kvm_create_device {
            type_: kvm_device_type_KVM_DEV_TYPE_ARM_VGIC_V2,
            fd: 0,
            flags: KVM_CREATE_DEVICE_TEST,
        };

        if vm.create_device(&mut gic_device).is_ok() {
            assert!(vm.create_irq_chip().is_ok());
        } 
    }
```

The problem of the code is that it seems not practical, after all `create_device()` itself can be used to create either GICv2 or GICv3, and it is the preferred way.

Any idea?
